export const sorts = [
  // {
  //   title: "Date",
  //   child: null,
  //   kind: "date",
  // },
  // {
  //   title: "Meal",
  //   child: [
  //     "Breakfast",
  //     "Brunch",
  //     "Lunch",
  //     "Snacks",
  //     "Dinner",
  //     "Dessert",
  //     "Drinks",
  //   ],
  //   kind: "list",
  // },
  {
    title: "Special Features",
    child: [
      "Vegetarian",
      "Vegan",
      "Bio",
      "Lactose-free",
      "Halal",
      "Gluten-free",
      "Alcohol-free",
      "Nut-free",
      "Sugar-free",
      "Low-carb / Keto",
      "High Protein",
      "Organic",
      "Low-fat",
      "Dairy-free",
      "Egg-free",
      "Soy-free",
      "No added preservatives",
      "Calorie-conscious",
    ],
    kind: "checkbox",
  },

  {
    title: "Pickup Time",
    kind: "time",
  },
  { title: "Price", child: [0, 1000], kind: "dual-slider" },
  // {
  //   title: "Location",
  //   child: ["Munich", "Berlin", "Dormund", "Hamburg", "Leipzig", "Heidelberg"],
  //   kind: "list",
  // },
  {
    title: "Rating",
    child: [
      "1 star and higher",
      "2 star and higher",
      "3 star and higher",
      "4 star and higher",
    ],
    kind: "checkbox",
  },
  {
    title: "Listing by Seller",
    child: null,
    kind: null,
  },
  {
    title: "Listing by Buyer",
    child: null,
    kind: null,
  },
  {
    title: "Sort By",
    child: [
      "Top Picks",
      "Price (lowest first)",
      "Price (highest first)",
      "Best Rated & Affordable",
      "Rating (high to low)",
      "Rating (low to high)",
      "Most Ordered",
      "New arrivals",
      "Recently added",
    ],
    kind: "list",
  },
];
